[package]
name = "tfschema-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.27", features = ["derive"] }
erased-serde = "0.3.23"
once_cell = "1.16.0"
quote = "1.0.21"
rustfmt = "0.10.0"
serde = "1.0.147"
serde_json = "1.0.89"
slog = "2.7.0"
sloggers = "2.1.1"
structre = "0.0.1"
syn = "1.0.103"
tempfile = "3.3.0"
